-- AlterTable
ALTER TABLE "bulk_ticket_orders"
  ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT,
  ADD COLUMN IF NOT EXISTS "senderPhone" TEXT,
  ADD COLUMN IF NOT EXISTS "trxId" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT,
  ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "approvedBy" TEXT,
  ALTER COLUMN "status" SET DEFAULT 'PENDING_APPROVAL';
